/* Generated by IDL compiler version FreeDCE 1.1.0.7 with GNU Flex/Bison */
#ifndef dsm_v0_0_included
#define dsm_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#define dsm_mod (0x1c0b0000)
#define dsm_err_create_failed (0x1c0b0001)
#define dsm_err_file_io_error (0x1c0b0002)
#define dsm_err_open_failed (0x1c0b0003)
#define dsm_err_version (0x1c0b0004)
#define dsm_err_no_memory (0x1c0b0005)
#define dsm_err_duplicate_write (0x1c0b0006)
#define dsm_err_header_too_long (0x1c0b0007)
#define dsm_err_no_more_entries (0x1c0b0008)
#define dsm_err_invalid_handle (0x1c0b0009)
#define dsm_err_invalid_pointer (0x1c0b000a)
#define dsm_err_info_too_long (0x1c0b000b)
#define dsm_err_file_busy (0x1c0b000c)
#define dsm_err_invalid_marker (0x1c0b000d)
typedef idl_void_p_t dsm_handle_t;
typedef idl_ulong_int dsm_marker_t;
typedef struct dsm_stats_t {
idl_ulong_int size;
idl_ulong_int free_space;
idl_ulong_int largest_free;
} dsm_stats_t;
#define dsm_version (0x1)
#define dsm_hdr_size (0x30)
#define dsm_magic_marker (0xf000000f)
extern void dsm_create(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *fname,
    /* [out] */ dsm_handle_t *dsh,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_open(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *fname,
    /* [out] */ dsm_handle_t *dsh,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_close(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ dsm_handle_t *dsh,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_allocate(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_ulong_int len,
    /* [out] */ idl_void_p_t *p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_write(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_write_hdr(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [in] */ idl_ulong_int len,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_free(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_detach(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_get_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t info,
    /* [in] */ idl_ulong_int len,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_set_info(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t info,
    /* [in] */ idl_ulong_int len,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_read(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in, out] */ dsm_marker_t *marker,
    /* [out] */ idl_void_p_t *p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_marker_reset(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ dsm_marker_t *marker
#endif
);
extern void dsm_locate(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ dsm_marker_t marker,
    /* [out] */ idl_void_p_t *p,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_inq_marker(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [out] */ dsm_marker_t *marker,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_inq_size(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [in] */ idl_void_p_t p,
    /* [out] */ unsigned32 *size,
    /* [out] */ error_status_t *st
#endif
);
extern void dsm_get_stats(
#ifdef IDL_PROTOTYPES
    /* [in] */ dsm_handle_t dsh,
    /* [out] */ dsm_stats_t *stats,
    /* [out] */ error_status_t *st
#endif
);
extern idl_boolean dsm_reclaim(
#ifdef IDL_PROTOTYPES
    /* [in, out] */ dsm_handle_t *dsh,
    /* [in] */ idl_char *fname,
    /* [in] */ idl_char *tempname,
    /* [in] */ idl_char *oldname,
    /* [in] */ unsigned32 free_pct,
    /* [out] */ error_status_t *st
#endif
);

#ifdef __cplusplus
    }
#endif

#endif
