/* include/config.h.  Generated automatically by configure.  */
/* generated by configure */

/*  */
#define YYTEXT_POINTER 1

/*  */
#define SIZEOF_INT 4

/*  */
#define SIZEOF_LONG 4

/*  */
#define SIZEOF_SHORT 2

/*  */
#define HAVE_LIBPTHREAD 1

/*  */
#define HAVE_LIBDL 1

/*  */
#define HAVE_FEATURES_H 1

/*  */
#define HAVE_SYS_CDEFS_H 1

/*  */
#define HAVE_DLFCN_H 1

/*  */
#define HAVE_UNISTD_H 1

/*  */
#define HAVE_STDLIB_H 1

/*  */
#define HAVE_FILE_MACRO 1

/*  */
#define HAVE_FUNCTION_MACRO 1

/* Ask for re-entrant api */
#define _REENTRANT 1

/* Ask for gnu extensions */
#define _GNU_SOURCE 1

/* Tell libc that we want BSD things */
#define _BSD 1

/* Compile with debugging support */
#define DEBUG_ENABLE 1


